# Generated by Django 5.1.1 on 2024-09-11 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_oneidprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='oneidprofile',
            index=models.Index(fields=['user'], name='users_oneid_user_id_7ed807_idx'),
        ),
    ]
