# Generated by Django 5.1.1 on 2024-09-11 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_spy', '0002_alter_report_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at', 'user'], name='petrol_spy__created_0efaf6_idx'),
        ),
    ]
